name: HospFlow
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0' # Subimos levemente o requisito do Dart

dependencies:
  flutter:
    sdk: flutter
  
  signature: ^5.5.0
  sqflite: ^2.3.0
  path: 1.9.0 
  intl: ^0.18.0
  image_picker: ^1.0.7
  
  # --- A MUDANÇA QUE RESOLVE O BUG ---
  # Versões antigas dão erro de "Embedding V2" falso.
  # Usamos a versão 0.13.0 que corrige isso.
  google_mlkit_text_recognition: ^0.13.0 
  # -----------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Ajustado para compatibilidade
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/icon.png"
