name: HospFlow
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Assinatura
  signature: ^5.5.0
  
  # Banco de Dados
  sqflite: ^2.3.0
  
  # --- CORREÇÃO CRÍTICA ---
  # Deve ser exatamente 1.9.0 para não dar conflito no GitHub Actions
  path: 1.9.0 
  # ------------------------

  # Formatação de datas
  intl: ^0.18.0
  
  # Câmera
  image_picker: ^1.0.7
  
  # OCR (Leitura de Texto)
  google_mlkit_text_recognition: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

# Configuração do Ícone
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/icon.png"
